version: "3"
services:
  web:
   container_name: webserver_1
   image: nginxphp:latest
   ports:
    - "8888:80"       
   volumes:
    - ./index:/var/www/myapp
    - ./conf.d:/etc/nginx/conf.d  
   networks:
    - phpnginx
          
  php:
   container_name: webapp_1
   depends_on:
    - db        
   image: phamtuan4nh/php_mysqli
   volumes:
    - ./index:/var/www/myapp
   expose:
    - 9000
   networks:
    - phpnginx
  db:
   container_name : dataweb_1
   image: mysql:8.0
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: webdata
     MYSQL_USER: pta
     MYSQL_PASSWORD: pta150691
   ports:
     - "6033:3306"
   networks:
     - phpnginx       
networks:
  phpnginx:      
